### ISSUE TITLE
When will the done event be fired for a stopwatch?

### ISSUE THREAD

**Issue by icyflame** [MickCrozier/timer-stopwatch#2]
If I start a stopwatch with:

``` javascript
var stopwatch = new Stopwatch();
```

I have seen that calling `stopwatch.stop()` does not fire the event `done` for this stopwatch instance.

Is there any other case in which the `done` event will be fired for a stopwatch?

**Comment by MickCrozier** [comment]
Hi icyflame
Stop() stops the stopwatch at its current time - the done event will only fire when the remaining time equals 0.

**Comment by icyflame** [comment]
@MickCrozier 
So, for a stopwatch, the remaining time can never be zero, right? (Since we are counting up from 0)

**Comment by icyflame** [comment]
@MickCrozier 
I have updated the description now. My earlier description was confusing, sorry.

**Comment by MickCrozier** [comment]
Ah, yes - lol. Stopwatch counts up

That's right.
You can always:

``` javascript
myStopwatch.stop();
myFunctionInsteadAnEvent(myStopwatch.ms);
```

Oh - startstop() - will return false for stopped and true for running

**Comment by MickCrozier** [comment]
You can also check the 'runTimer' property for the running state.

Have been meaning to add getter/setter functions for these to make it straight forward.

**Comment by icyflame** [comment]
@MickCrozier 
Definitely! And `startstop()` would return a boolean?

You may want to use some kind of an automatic documentation generator of some kind! To get a concise document that has the prototypes of all the functions!

**Comment by MickCrozier** [comment]
@icyflame 
Yep - Inline documentation is always on my list, but somehow I always get caught up - lol

**Comment by icyflame** [comment]
@MickCrozier 
I did it! I had some time, and it the `startstop` function thingy, really did reel me out! :smile: 

Do check my PR #5 , we can do a review and merge!

I have fired an event when the timer is force stopped by the user!

**Comment by MickCrozier** [comment]
Hell yeah! thank you!
