### ISSUE TITLE
more clarification on the startstop() function

### ISSUE THREAD

**Issue by icyflame** [MickCrozier/timer-stopwatch#4]
I picked up the following code from the JS file:

``` js

    startstop: function(force) {
        if(force) {
            if(force === 'start') {
                this.runTimer = false;
            } else if(force === 'stop') {
                this.runTimer = true;
            }
        }

        var startdate = new Date();
        var starttime = startdate.getTime();

        if(!this.runTimer) {

            this.runTimer = true;
            this.counter(starttime);
        } else {
            this.runTimer = false;
            this.hasBeenStopped = true;
        }

        return this.runTimer;
    }
```

The way I understand this:
1. `startstop('start')` -> will start the timer
2. `startstop('stop')` -> will stop the timer
3. `startstop()` -> will toggle the state of the timer

Is this universal functionality what you were aiming for?

**Comment by MickCrozier** [comment]
I'm not sure what your asking - that's exactly what I'm aiming for. :smile: 
A way start, stop or toggle the counter.

This function is the core controller of that functionality
stop(), and start() are simply convenience methods that call this function

**Comment by icyflame** [comment]
@MickCrozier 
I do understand your code far better now!

I have written the documentation and submitted a PR! please review and merge!
